---
- name: Check if application exists
  stat:
    path: "{{ item.path | default('/Applications/' + item.name + '.app') }}"
  loop: "{{ cask_apps }}"
  register: cask_app_st
  changed_when: false

- name: Install application with Homebrew cask
  when: not item.stat.exists
  set_fact:
    homebrew_cask_apps: "{{ homebrew_cask_apps + ( item.item.apps | default([ item.item.app | default(item.item.name|lower|replace(' ','-')) ]) ) }}"
  loop: "{{ cask_app_st.results }}"
