---
- name: Check if ~/.bash_profile exists
  stat:
    path: "{{ bash_home }}/.bash_profile"
  register: bash_profile_st
  changed_when: false

- name: Create empty ~/.bash_profile file
  file:
    path: "{{ bash_home }}/.bash_profile"
    state: touch
    mode: "0644"
  when: not bash_profile_st.stat.exists

- name: Check if ~/.bashrc exists
  stat:
    path: "{{ bash_home }}/.bashrc"
  register: bashrc_st
  changed_when: false

- name: Create empty ~/.bashrc file
  file:
    path: "{{ bash_home }}/.bashrc"
    state: touch
    mode: "0644"
  when: not bashrc_st.stat.exists

- name: Check whether ~/.bashrc is loaded from ~/.bash_profile
  command: grep -Fxq "source ~/.bashrc" {{ bash_home }}/.bash_profile
  register: check_bashrc
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Load ~/.bashrc from ~/.bash_profile
  blockinfile:
    dest: "{{ bash_home }}/.bash_profile"
    block: |
      if [ -f ~/.bashrc ]; then
        source ~/.bashrc
      fi
  when: check_bashrc.rc != 0
