---

- name: Setup variables and check requirements
  hosts: all
  tags:
    - always
  tasks:

    - name: Check that we're running macOS
      assert:
        that:
          - "ansible_os_family == 'Darwin'"
        msg: "This playbook only supports macOS systems"

- import_playbook: macos.yml
- import_playbook: tools.yml
- import_playbook: editors.yml
- import_playbook: git.yml
- import_playbook: asdf.yml

- import_playbook: front-end-toolkit.yml
- import_playbook: python.yml
- import_playbook: vagrant.yml
- import_playbook: docker.yml
- import_playbook: gcloud.yml
- import_playbook: aws.yml
- import_playbook: hashicorp.yml
- import_playbook: golang.yml
- import_playbook: devops.yml
- import_playbook: secops.yml
