---

- name: Setup variables and check requirements
  hosts: all
  tasks:

    - name: Check that we're running macOS
      assert:
        that:
          - "ansible_os_family == 'Darwin'"
        msg: "This playbook only supports macOS systems"

- include: macos.yml
- include: tools.yml
- include: editors.yml
- include: git.yml
- include: front-end-toolkit.yml
- include: python.yml
- include: vagrant.yml
- include: docker.yml
- include: gcloud.yml
- include: aws.yml
- include: hashicorp.yml
- include: golang.yml
- include: devops.yml
- include: secops.yml
